import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Great_Vibes } from "next/font/google";
import { Shantell_Sans } from "next/font/google";
import { Onest } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const greatVibes = Great_Vibes({
  weight: '400',
  subsets: ["cyrillic"],
  display: 'swap',
  variable: '--font-great-vibes',
});

const shantellSans = Shantell_Sans({
  weight: '400',
  subsets: ["cyrillic"],
  display: 'swap',
  variable: '--font-shantell'
})

const onestFont = Onest({
  weight: ['400', '700'],
  subsets: ["cyrillic"],
  display: 'swap',
  variable: '--font-onest'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${onestFont.variable} ${shantellSans.variable} ${greatVibes.variable} ${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
